[FIX] purchase_ux: net_price in PO_line
ingadhoc/purchase pull request #175
Opened 2024-01-04 21:28 UTC by mav-adhoc

2024-01-04 21:29 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/purchase/pull/175).

2024-01-10 16:44 UTC, augusto-weiss requested changes

2024-01-10 16:44 UTC, augusto-weiss commented on purchase_ux/models/purchase_order_line.py
> +            line._compute_price_unit_and_date_planned_and_name()
```
        lines._compute_price_unit_and_date_planned_and_name()
```

2024-01-11 14:51 UTC, augusto-weiss commented
@roboadhoc r+

2024-01-11 14:55 UTC, closed without merging