[FIX] related to standard_price using in the user company currency li…
ingadhoc/purchase pull request #53
Opened 2019-01-18 16:04 UTC by nicomacr

…ke odoo use for all

2019-01-18 16:06 UTC, nicomacr commented
for this before need to approve this [PR](https://github.com/ingadhoc/product/pull/183)

2019-02-08 12:29 UTC, jjscarafia requested changes
@nicomacr van algunos comentarios que son para que funcione bien si uno hace ordenes de compra en companias que no es donde está parado el usuario.

2019-02-08 12:29 UTC, jjscarafia commented on purchase_ux/models/procurement_rule.py
>              price_unit = product_id.standard_price
acá habria que mandar force_company=values['company_id'].id para garantizar tomar property de la company que corresponde

2019-02-08 12:29 UTC, jjscarafia commented on purchase_ux/models/procurement_rule.py
> +                    po.currency_id != product_id.user_company_currency_id):
acá definiría una variable tipo
company_currency = values['company_id'].currency_id.id y luego usaría esa en vez de la "user_company_currency_id"

2019-02-08 12:29 UTC, jjscarafia commented on purchase_ux/models/purchase_order_line.py
> +                price_unit = self.product_id.user_company_currency_id.compute(
acá también, en vez de usar la "user_company_currency_id" debeŕiamos usar la  "self.order_id.company_id.currency_id"

2019-02-08 12:29 UTC, jjscarafia commented on purchase_ux/models/purchase_order_line.py
>              price_unit = self.product_id.standard_price
acá deberíamos mandar el force_company=self.order_id.company_id.id

2019-02-08 18:06 UTC, merged